version: '3.8'

services: 

  client:
    build: 
      context: ./typing-client
      dockerfile: Dockerfile
    
    tty: true
    ports: 
      - "3000:3000"
    
    volumes: 
      - ./frontend:/app
      - /app/node_modules