name: pytesting

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          cd ${{ github.workspace }}/typing-server
          pip install flake8
          pip install -r requirements.txt
      
      - name: Run tests with Pytest
        working-directory: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}/typing-server
          pytest
