name: Python Pytest CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f typing-server/requirements.txt]; then pip install -r typing-server/requirements.txt; fi
      
      - name: Run tests with Pytest
        run: |
          cd typing-server
          pytest
