name: Python Pytest CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/typing-server
        run: |
          python -m pip install --upgrade pip
          echo ${{ github.workspace }}
          pip install flake8
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi
      
      - name: Run tests with Pytest
        working-directory: ${{ github.workspace }}/typing-server
        run: |
          pytest
